### PR TITLE
Add 'Scroll back to top' button

### PR DESCRIPTION
**Pull request by MehekFatima**
I have created a pull request to add a 'Scroll back to top' button to the website. The button appears when the user scrolls down and, when clicked, scrolls the page back to the top.

Please review my PR and let me know if there are any changes or improvements needed. @Njoguu 

Thank you!

### CODE REVIEW

**Comment by Njoguu** [comment]
Hello @MehekFatima. Please adjust the height and width of the `#scrollToTopBtn` to `54px`. Thank you.

**Comment by MehekFatima** [comment]
hi, okay sure @Njoguu

**Comment by MehekFatima** [comment]
Hey @Njoguu , I've made  adjustments to the scrollToTop button as you suggested.  Please review my PR.
Thanks!

**Review by Njoguu — APPROVED** [review]
looks good to me

**Pull request merged**
